export enum DatastoreKeys {
    AuthToken = 'authToken',
    AuthErrors = 'authErr',
    AuthSettings = 'authConfig',
    AuthIdpConfig = 'authIdp',
    AppLogs = 'appLogs',
    // Do we really need these?
    QueryString = 'qrystr',
    SessionId = 'sessionId',
    AgentSessionInfo = 'agentSessionInfo',
    AgentLeg = 'agentLeg',
    LocalTime = 'localTime',
    ServerTime = 'serverTime',
    StateInfo = 'stateInfo',
    AgentMessages = 'agentMsgs',
    BusinessUnit = 'businessUnit',
    Permissions = 'permissions',
    AgentSettings = 'agentSettings',
    AgentInfo = 'agentInfo',
    UnavailableCodes = 'unavailableCodes',
    DisableAutoLogin = 'disableAutoLogin',
    InitParam = 'initParam',
    RefreshTokenError = 'refreshTokenError',
    RouterUrl = 'routerUrl',
    CallContacts = 'callContacts',
    SfResult = 'sfResult',
    SFSessionId = 'sfSessionId',
    AgentSkillList = 'agentSkillList',
    Cx1Tab = 'cx1Tab',
    IsCx1Open = 'isCX1Open',
    WfoUrl = 'wfoUrl',
    TimezonesList = 'timezonesList',
    SkillMediaType = 'skillMediaType',
    AgentMuted = 'agentMuted',
    Indicators = 'Indicators',
    CommitmentReminderData = 'commitmentReminderData',
    LastAttentedContactId = 'lastAttentedContactId',
    LastDispoContactId = 'lastDispoContactId',

    NewUserId = "newUserUUID",
    TenantId = "tenantId",
    AccessSecretKey = "accessSecretKey",
    EvolveWebServerUrl = "evolveWebServerUrl",
    AdminUserName = "adminUserName"
}
